# Generated by Django 6.0.4 on 2026-04-30 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_team_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("verified", "검증 완료"),
                    ("rejected", "거절됨"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="topic",
            field=models.TextField(blank=True, verbose_name="문서 토픽"),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
