# Generated by Django 6.0.4 on 2026-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_projectfile_status_projectfile_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="content",
            field=models.TextField(blank=True, verbose_name="검증 내용 (텍스트)"),
        ),
    ]
