# Generated by Django 6.0.4 on 2026-04-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projectreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("highlighted_text", models.TextField(verbose_name="해당 내용")),
                ("problem", models.TextField(verbose_name="문제점")),
                ("suggestion", models.TextField(verbose_name="제안 내용")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="core.projectfile",
                    ),
                ),
            ],
            options={"verbose_name": "AI 검증 항목", "ordering": ["order"],},
        ),
    ]
